#ifndef ERROR_CODES_H
#define ERROR_CODES_H

typedef enum {
    RESULT_SUCCESS = 1,
    RESULT_FAILURE = 0,

    RESULT_EMPTY_INPUT = -1,
    RESULT_INVALID_INPUT = -2,
    RESULT_UNSUPPORTED_CHARACTER = -3,
    RESULT_INVALID_MORSE = -4,

    RESULT_FILE_OPEN_ERROR = -10,
    RESULT_FILE_WRITE_ERROR = -11,

    RESULT_INVALID_SEPARATOR = -20,

    RESULT_SETTINGS_LOAD_ERROR = -30,
    RESULT_SETTINGS_SAVE_ERROR = -31
} ResultCode;

#endif