#ifndef LANGUAGE_H
#define LANGUAGE_H

typedef enum {
    TXT_CHOOSE_OPTION,
    TXT_PRESS_ENTER,

    TXT_MAIN_TITLE,
    TXT_MENU_TEXT_TO_MORSE,
    TXT_MENU_MORSE_TO_TEXT,
    TXT_MENU_FILE_TEXT_TO_MORSE,
    TXT_MENU_FILE_MORSE_TO_TEXT,
    TXT_MENU_SHOW_TABLE,
    TXT_MENU_ABOUT,
    TXT_MENU_SETTINGS,
    TXT_MENU_EXIT,

    TXT_SETTINGS_TITLE,
    TXT_CURRENT_SEPARATOR,
    TXT_CURRENT_LANGUAGE,
    TXT_CHANGE_SEPARATOR,
    TXT_CHANGE_LANGUAGE,
    TXT_BACK,

    TXT_SEPARATOR_SAVED,
    TXT_LANGUAGE_SAVED,
    TXT_NEW_SEPARATOR,
    TXT_NEW_LANGUAGE,

    TXT_TITLE_TEXT_TO_MORSE,
    TXT_TITLE_MORSE_TO_TEXT,
    TXT_TITLE_FILE_TEXT_TO_MORSE,
    TXT_TITLE_FILE_MORSE_TO_TEXT,
    TXT_TITLE_MORSE_TABLE,
    TXT_TITLE_CHANGE_SEPARATOR,
    TXT_TITLE_CHANGE_LANGUAGE,

    TXT_ENTER_TEXT,
    TXT_ENTER_MORSE_CODE,
    TXT_ENTER_INPUT_FILE_NAME,
    TXT_ENTER_MORSE_FILE_NAME,
    TXT_ENTER_NEW_SEPARATOR,
    TXT_ENTER_NEW_LANGUAGE,

    TXT_MORSE_OUTPUT,
    TXT_TEXT_OUTPUT,
    TXT_INPUT_FILE_PREVIEW,
    TXT_MORSE_OUTPUT_PREVIEW,
    TXT_MORSE_INPUT_FILE_PREVIEW,
    TXT_DECODED_TEXT_PREVIEW,
    TXT_DETECTED_SEPARATOR,

    TXT_FILE_CONVERTED_SUCCESSFULLY,
    TXT_OUTPUT_SAVED_SUCCESSFULLY,
    TXT_DO_YOU_WANT_TO_SAVE,
    TXT_EXITING_IN_SECONDS,

    TXT_CONVERSION_STATISTICS,
    TXT_INPUT_LENGTH,
    TXT_OUTPUT_LENGTH,
    TXT_WORD_COUNT,
    TXT_CONVERTED_CHARACTERS,
    TXT_SPACE_COUNT,

    TXT_SESSION_SUMMARY,
    TXT_TEXT_TO_MORSE_OPERATIONS,
    TXT_MORSE_TO_TEXT_OPERATIONS,
    TXT_FILE_OPERATIONS,
    TXT_INVALID_INPUTS,
    TXT_SAVED_OUTPUTS,

    TXT_CURRENT_SEPARATOR_SHORT,
    TXT_ALLOWED_SEPARATORS,
    TXT_ALLOWED_LANGUAGES,

    TXT_ABOUT_TITLE,
    TXT_ABOUT_DESCRIPTION,
    TXT_ABOUT_DEMONSTRATES,
    TXT_ABOUT_2D_ARRAY,
    TXT_ABOUT_FILE_IO,
    TXT_ABOUT_STRING_OPERATIONS,
    TXT_ABOUT_MODULAR_DESIGN,
    TXT_ABOUT_HEADER_SOURCE,
    TXT_ABOUT_SWITCH_CASE,
    TXT_ABOUT_INPUT_VALIDATION,
    TXT_ABOUT_TURKISH_NORMALIZATION,
    TXT_ABOUT_AUTO_FILE_NAMING,
    TXT_ABOUT_PERSISTENT_SETTINGS,
    TXT_ABOUT_STRUCT_POINTER,
    TXT_ABOUT_AUTHOR,
    TXT_ABOUT_STUDENT_NUMBER,

    TXT_ERROR_UNKNOWN,
    TXT_ERROR_EMPTY_INPUT,
    TXT_ERROR_INVALID_INPUT,
    TXT_ERROR_UNSUPPORTED_CHARACTER,
    TXT_ERROR_INVALID_MORSE,
    TXT_ERROR_FILE_OPEN,
    TXT_ERROR_FILE_WRITE,
    TXT_ERROR_INVALID_SEPARATOR,
    TXT_ERROR_SETTINGS_LOAD,
    TXT_ERROR_SETTINGS_SAVE
} LanguageTextKey;

const char* getText(const char language[], LanguageTextKey key);
int isSupportedLanguage(const char language[]);

#endif